name: K6 Load Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  k6_load_test:
    name: k6 Load Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install k6
        run: |
          curl -sSL https://dl.k6.io/get-k6 | bash
          
      - name: Run k6 tests
        run: |
          k6 run -o json=results.json 1-script.js
          
      - name: Upload performance test results
        uses: actions/upload-artifact@v2
        with:
          name: k6-report
          path: results.json
