name: K6 Load Tests

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
 build:

    name: K6 Load Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run cloud k6 test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: 1-script.js
          cloud: true
          token: ${{ secrets.K6_CLOUD_API_TOKEN }}